/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package swing;

import javax.swing.JOptionPane;
import projet3_api.metier.Bureau;
import Bureau.DAO.EmployeDAO;
import projet3_api.metier.Employe;

/**
 *
 * @author David
 */
public class CreationEmploye_jpanel extends javax.swing.JPanel {
    EmployeDAO employeDAO=null;
    /**
     * Creates new form CreationEmploye_jpanel
     */
    public CreationEmploye_jpanel() {
        initComponents();
    }
    public void setEmployeDAO(EmployeDAO employeDAO){
        this.employeDAO=employeDAO;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Matricule_form = new javax.swing.JTextField();
        Nom_form = new javax.swing.JTextField();
        Prenom_form = new javax.swing.JTextField();
        Idbur_form = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        idemp_form = new javax.swing.JTextField();

        jLabel1.setText("Matricule");

        jLabel2.setText("Nom");

        jLabel3.setText("Prenom");

        jLabel4.setText("Idbur");

        Matricule_form.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Matricule_formActionPerformed(evt);
            }
        });

        Nom_form.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Nom_formActionPerformed(evt);
            }
        });

        Idbur_form.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Idbur_formActionPerformed(evt);
            }
        });

        jButton1.setText("creation");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel5.setText("Idemp");

        idemp_form.setEditable(false);
        idemp_form.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idemp_formActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addGap(111, 111, 111)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton1)
                    .addComponent(Matricule_form, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                    .addComponent(Nom_form)
                    .addComponent(Prenom_form)
                    .addComponent(Idbur_form)
                    .addComponent(idemp_form))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(22, 22, 22))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(idemp_form, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(Matricule_form, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(Nom_form, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(35, 35, 35)
                        .addComponent(jLabel3))
                    .addComponent(Prenom_form, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addComponent(Idbur_form, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void Nom_formActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Nom_formActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Nom_formActionPerformed

    private void Matricule_formActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Matricule_formActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Matricule_formActionPerformed

    private void Idbur_formActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Idbur_formActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Idbur_formActionPerformed

    private void idemp_formActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idemp_formActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idemp_formActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
            try{
            //int idbur=Integer.parseInt(idbur_form1.getText());
            
            String matricule=Matricule_form.getText();
            String nom=Nom_form.getText();
            String prenom=Prenom_form.getText();
            int idbur=Integer.parseInt(Idbur_form.getText());
            Employe em=new Employe(0,matricule,nom,prenom,idbur);
            em=employeDAO.create(em);
            idemp_form.setText(""+em.getIDEMP());
            JOptionPane.showMessageDialog(this,"employe créé","succès",JOptionPane.INFORMATION_MESSAGE);

        }catch(Exception e){
                    JOptionPane.showMessageDialog(this,e.getMessage(),"ERREUR",JOptionPane.ERROR_MESSAGE);
}
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    javax.swing.JTextField Idbur_form;
    private javax.swing.JTextField Matricule_form;
    private javax.swing.JTextField Nom_form;
    private javax.swing.JTextField Prenom_form;
    private javax.swing.JTextField idemp_form;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables

   
}
