/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package swing;

import java.awt.CardLayout;
import java.sql.Connection;
import javax.swing.JOptionPane;
import Bureau.DAO.EmployeDAO;
import Bureau.DAO.BureauDAO;
import Bureau.DAO.DAO;
import myconnections.DBConnection;
/**
 *
 * @author David
 */
public class Gestion_Employe_jframe extends javax.swing.JFrame {

    /**
     * Creates new form Gestion_Employe_jframe
     */
     CardLayout cardl;
    public Gestion_Employe_jframe() {
        initComponents();
         cardl=(CardLayout)this.getContentPane().getLayout();
         Connection dbConnect = DBConnection.getConnection();
        if (dbConnect == null) {
            System.out.println("connection invalide");
            JOptionPane.showMessageDialog(this,"connexion invalide","ERREUR",JOptionPane.ERROR_MESSAGE);
        }
         EmployeDAO employeDAO = new EmployeDAO();
         employeDAO.setDbConnect(dbConnect);
         creationEmploye_jpanel1.setEmployeDAO(employeDAO);
         rechercheEmploye_jpanel1.setEmployeDAO(employeDAO);
         
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        creationEmploye_jpanel1 = new swing.CreationEmploye_jpanel();
        rechercheEmploye_jpanel1 = new swing.RechercheEmploye_jpanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuGestionEmploye = new javax.swing.JMenu();
        jMenuItemcrea = new javax.swing.JMenuItem();
        jMenuItemrech = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.CardLayout());
        getContentPane().add(creationEmploye_jpanel1, "card2");
        getContentPane().add(rechercheEmploye_jpanel1, "card3");

        jMenuBar1.setBackground(new java.awt.Color(51, 204, 255));
        jMenuBar1.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 0, 204), new java.awt.Color(102, 255, 255)));
        jMenuBar1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jMenuGestionEmploye.setText("Menu Employe");

        jMenuItemcrea.setText("Creation Employe");
        jMenuItemcrea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemcreaActionPerformed(evt);
            }
        });
        jMenuGestionEmploye.add(jMenuItemcrea);

        jMenuItemrech.setText("Recherche Employe");
        jMenuItemrech.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemrechActionPerformed(evt);
            }
        });
        jMenuGestionEmploye.add(jMenuItemrech);

        jMenuBar1.add(jMenuGestionEmploye);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemrechActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemrechActionPerformed
         cardl.show(this.getContentPane(), "card3");
    }//GEN-LAST:event_jMenuItemrechActionPerformed

    private void jMenuItemcreaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemcreaActionPerformed
         cardl.show(this.getContentPane(), "card2");
    }//GEN-LAST:event_jMenuItemcreaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Gestion_Employe_jframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Gestion_Employe_jframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Gestion_Employe_jframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Gestion_Employe_jframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Gestion_Employe_jframe().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private swing.CreationEmploye_jpanel creationEmploye_jpanel1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuGestionEmploye;
    private javax.swing.JMenuItem jMenuItemcrea;
    private javax.swing.JMenuItem jMenuItemrech;
    private swing.RechercheEmploye_jpanel rechercheEmploye_jpanel1;
    // End of variables declaration//GEN-END:variables
}
